# Generated by Django 6.0.6 on 2026-06-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bank_account_number',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bank_branch',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='ifsc_code',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
