# Generated by Django 6.0.6 on 2026-06-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
