# Generated by Django 6.0.6 on 2026-06-23 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_student_password_student_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='School Event', max_length=100)),
                ('description', models.TextField(blank=True, default='No Description Available')),
                ('event_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(default='unknown_user', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
